version: "3.9"

services:
  db:
    container_name: database
    image: mysql
    restart: always
    env_file:
      - database_config/mysql.env
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
  web:
    container_name: server
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db:
    driver: local